/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ProdutoDao;
import DTO.CadProdutoDTO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gabrielly
 */
public class FrmCadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroProduto
     */
    public FrmCadastroProduto() {
        initComponents();
        jPanel1.setBackground(new java.awt.Color(255, 228, 225));
    jPanel1.setOpaque(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtFornProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        intQuantProd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecoVend = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTipoProd = new javax.swing.JTextField();
        btnProximo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMarcaProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jCheckBox1.setText("jCheckBox1");

        jPanel1.setForeground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtFornProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 356, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Quantidade:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        jPanel3.add(intQuantProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 356, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Preço de Venda:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));
        jPanel3.add(txtPrecoVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 356, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de Produto:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));
        jPanel3.add(txtTipoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 356, -1));

        btnProximo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        jPanel3.add(btnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Cadastro de Produtos");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 290, 40));

        txtMarcaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaProdActionPerformed(evt);
            }
        });
        jPanel3.add(txtMarcaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 356, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Fornecedor:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Marca");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel3.add(txtNomeProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 356, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome do produto:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        txtCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 356, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Código de Barras:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaProdActionPerformed
        txtFornProd.requestFocus();
    }//GEN-LAST:event_txtMarcaProdActionPerformed

    private void txtCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdActionPerformed
        txtNomeProd.requestFocus();
    }//GEN-LAST:event_txtCodProdActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        int codProduto; //id
        String nomeProduto;
        String marcaProduto;
        String fornecedorProd;
        int quantProd;
        double precoVenda;
        String tipoProduto; 
        
        codProduto = Integer.parseInt(txtCodProd.getText()); 
        nomeProduto = txtNomeProd.getText();
        marcaProduto= txtMarcaProd.getText();
        fornecedorProd = txtFornProd.getText();
        quantProd = Integer.parseInt(intQuantProd.getText());
        precoVenda = Double.parseDouble(txtPrecoVend.getText());
        tipoProduto = txtTipoProd.getText();
        
        CadProdutoDTO objProdutoDto = new CadProdutoDTO();
        objProdutoDto.setCodProduto(codProduto); 
        objProdutoDto.setNomeProduto(nomeProduto);
        objProdutoDto.setMarcaProduto(marcaProduto);
        objProdutoDto.setFornecedorProd(fornecedorProd);
        objProdutoDto.setQuantProd(quantProd);
        objProdutoDto.setPrecoVenda(precoVenda);
        objProdutoDto.setTipoProduto(tipoProduto);
        
        ProdutoDao objProdutoDao = new ProdutoDao();
        try {
            objProdutoDao.cadastrarProduto(objProdutoDto);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnProximoActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
    
    try {
        javax.swing.UIManager.put("Panel.background", new java.awt.Color(255, 228, 225)); // Rosa claro
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

   
    java.awt.EventQueue.invokeLater(() -> {
        FrmCadastroProduto frame = new FrmCadastroProduto();
        frame.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximo;
    private javax.swing.JTextField intQuantProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtFornProd;
    private javax.swing.JTextField txtMarcaProd;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtPrecoVend;
    private javax.swing.JTextField txtTipoProd;
    // End of variables declaration//GEN-END:variables
}
